name: Hank Quinlan, Horrible Cop
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

# This URL is the main address for absolute links. Don't include a slash at the end.
url: 'https://singularityhacker.github.io'
baseurl: '/jekyll-tests'
